### ISSUE TITLE
Broken images links in fieldguide log file

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/fieldguide#14]
There are messages about broken image links in the fieldguide log file. Not sure if these are preventing downloads completing, but it may be necessary to work through what is occurring (particularly with the rewrite of the image-service file storage backend occurring currently)

```
java.io.FileNotFoundException: https://images.ala.org.au/image/proxyImage?imageId=bddf58a2-0035-4182-a607-222cb0aea4f7
        at java.net.URL.openStream(URL.java:1068)
        at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1390)
        at au.org.ala.GenerateService$_cacheImages_closure1_closure7_closure8.doCall(GenerateService.groovy:114)
        at au.org.ala.GenerateService$_cacheImages_closure1_closure7.doCall(GenerateService.groovy:94)
        at au.org.ala.GenerateService$_cacheImages_closure1.doCall(GenerateService.groovy:93)
        at au.org.ala.GenerateService.cacheImages(GenerateService.groovy:92)
        at au.org.ala.GenerateService.generate(GenerateService.groovy:43)
        at au.org.ala.QueueService$ConsumerThread.run(QueueService.groovy:216)
```

**Comment by ansell** [comment]
A slightly different error with a similar apparently cause is:

```
2020-02-25 16:47:47,539 ERROR [ImageService] failed to get image metadata for: https://images.ala.org.au/image/proxyImage?imageId=bddf58a2-0035-4182-a607-222cb0aea4f7
java.io.FileNotFoundException: https://images.ala.org.au/ws/image/bddf58a2-0035-4182-a607-222cb0aea4f7
        at au.org.ala.ImageService.getInfo(ImageService.groovy:24)
        at au.org.ala.GenerateService$_getSortedTaxonInfo_closure2.doCall(GenerateService.groovy:158)
        at au.org.ala.GenerateService.getSortedTaxonInfo(GenerateService.groovy:155)
        at au.org.ala.GenerateService.generate(GenerateService.groovy:40)
        at au.org.ala.QueueService$ConsumerThread.run(QueueService.groovy:216)
```

**Comment by timhicks-ala** [comment]
Downloads fail silently when this issue occurs - no error message shown. This is often reported by users as simply never receiving the email with the link to the field guide.

User-reported query where creating a field guide fails due to this issue: https://biocache.ala.org.au/occurrences/search?q=*:*&lat=-42.9097&lon=147.2892&radius=1&fq=geospatial_kosher:true&fq=species_group:Plants

```
2020-08-03 11:50:14,368 ERROR [ImageService] failed to get image metadata for: https://images.ala.org.au/image/proxyImage?imageId=d1f2d55b-e690-4556-a817-2f62e50f568c
java.io.FileNotFoundException: https://images.ala.org.au/ws/image/d1f2d55b-e690-4556-a817-2f62e50f568c
	at au.org.ala.ImageService.getInfo(ImageService.groovy:24)
	at au.org.ala.GenerateService$_getSortedTaxonInfo_closure2.doCall(GenerateService.groovy:158)
	at au.org.ala.GenerateService.getSortedTaxonInfo(GenerateService.groovy:155)
	at au.org.ala.GenerateService.generate(GenerateService.groovy:40)
	at au.org.ala.QueueService$ConsumerThread.run(QueueService.groovy:216)
2020-08-03 11:50:14,868 ERROR [QueueService$ConsumerThread] Failed to generate fieldguide for: {"dwcHeaders":"true","controller":"generate","data":{"sortedTaxonInfo":"{={=[{scientificName=Campylium polygamum, nameComplete=Campylium polygamum (Schimp.) C.E.O.Jensen, author=(Schimp.) C.E.O.Jensen, datasetName=AusMoss, densitylegend=cache?id=httpsid.biodiversity.org.auinstanceausmoss10022599.legend.png, kingdom=null, densitymap=cache?id=httpsid.biodiversity.org.auinstanceausmoss10022599.png, phylum=null, classs=null, genus=null, linkIdentifier=Campylium_polygamum, name=Campylium polygamum, guid=https://id.biodiversity.org.au/instance/ausmoss/10022599, rank=species, datasetID=dr2703, family=null ...........................
```

**Comment by ansell** [comment]
@timhicks-ala @nickdos I opened a separate issue to send an email when fieldguide generation fails: #17

**Comment by nickdos** [comment]
I wonder if this is due to the preferred images list, where we've got taxon IDs and image UUIDs linked and images have been deleted? 

https://lists.ala.org.au/speciesListItem/list/dr4778

**Comment by ansell** [comment]
It should be possible to make the error non-fatal (still generate a fieldguide of sorts), and send an email (#17) while we work through what to do about deleted images and out-of-date lists.

**Comment by adam-collins** [comment]
Recent work as fixed the silent failing in image errors.
