### ISSUE TITLE
Cache collectionMetadata already exists error

### ISSUE THREAD

**Issue by ansell** [AtlasOfLivingAustralia/fieldguide#15]
The following showed up in the log files when attempting to restart `nectar-dashboard`:

```
==> /var/log/tomcat7/fieldguide.log <==
2020-02-26 14:40:43,077 ERROR [QueueService$ConsumerThread] Failed to generate fieldguide for: {"dwcHeaders":"true","controller":"generate","data":{"guids":["https://id.biodiversity.org.au/taxon/apni/51249803","https://id.biodiversity.org.au/node/apni/2893446","https://id.biodiversity.org.au/node/apni/5308808","https://id.biodiversity.org.au/node/apni/2897750","https://id.biodiversity.org.au/node/apni/8012087","https://id.biodiversity.org.au/node/apni/2891946","https://id.biodiversity.org.au/node/apni/2898281","https://id.biodiversity.org.au/node/apni/2898738","https://id.biodiversity.org.au/node/apni/2901867","https://id.biodiversity.org.au/node/apni/2912958","https://id.biodiversity.org.au/node/apni/2913383","https://id.biodiversity.org.au/node/apni/2919181","https://id.biodiversity.org.au/taxon/apni/51287115","https://id.biodiversity.org.au/taxon/apni/51300001","https://id.biodiversity.org.au/name/apni/249430","https://id.biodiversity.org.au/node/apni/2894437","https://id.biodiversity.org.au/node/apni/2898994","https://id.biodiversity.org.au/node/apni/2902214","https://id.biodiversity.org.au/node/apni/2910137","https://id.biodiversity.org.au/taxon/apni/51290024","https://id.biodiversity.org.au/name/apni/115902","https://id.biodiversity.org.au/name/apni/117422","https://id.biodiversity.org.au/node/apni/2888627","https://id.biodiversity.org.au/node/apni/2889450","https://id.biodiversity.org.au/node/apni/2892486","https://id.biodiversity.org.au/node/apni/2899243","https://id.biodiversity.org.au/node/apni/2900254","https://id.biodiversity.org.au/node/apni/2904543","https://id.biodiversity.org.au/node/apni/2907579","https://id.biodiversity.org.au/node/apni/2909241","https://id.biodiversity.org.au/node/apni/2909588","https://id.biodiversity.org.au/node/apni/2913979","https://id.biodiversity.org.au/node/apni/2914933","https://id.biodiversity.org.au/node/apni/2918410","https://id.biodiversity.org.au/node/apni/7387418","https://id.biodiversity.org.au/taxon/apni/51268348","https://id.biodiversity.org.au/taxon/apni/51269199","https://id.biodiversity.org.au/taxon/apni/51286863","https://id.biodiversity.org.au/taxon/apni/51290011","https://id.biodiversity.org.au/taxon/apni/51300819","ALA_Hypericum_japonicum_sensu_Allan","https://id.biodiversity.org.au/name/apni/119080","https://id.biodiversity.org.au/name/apni/230594","https://id.biodiversity.org.au/name/apni/51260715","https://id.biodiversity.org.au/name/apni/74094","https://id.biodiversity.org.au/name/apni/9392890","https://id.biodiversity.org.au/node/apni/2887052","https://id.biodiversity.org.au/node/apni/2887083","https://id.biodiversity.org.au/node/apni/2888307","https://id.biodiversity.org.au/node/apni/2888439","https://id.biodiversity.org.au/node/apni/2889241","https://id.biodiversity.org.au/node/apni/2890605","https://id.biodiversity.org.au/node/apni/2891651","https://id.biodiversity.org.au/node/apni/2892284","https://id.biodiversity.org.au/node/apni/2892288","https://id.biodiversity.org.au/node/apni/2892583","https://id.biodiversity.org.au/node/apni/2894213","https://id.biodiversity.org.au/node/apni/2895933","https://id.biodiversity.org.au/node/apni/2899343","https://id.biodiversity.org.au/node/apni/2899453","https://id.biodiversity.org.au/node/apni/2901138","https://id.biodiversity.org.au/node/apni/2901160","https://id.biodiversity.org.au/node/apni/2906122","https://id.biodiversity.org.au/node/apni/2906438","https://id.biodiversity.org.au/node/apni/2907368","https://id.biodiversity.org.au/node/apni/2908818","https://id.biodiversity.org.au/node/apni/2909697","https://id.biodiversity.org.au/node/apni/2910214","https://id.biodiversity.org.au/node/apni/2910974","https://id.biodiversity.org.au/node/apni/2911129","https://id.biodiversity.org.au/node/apni/2911274","https://id.biodiversity.org.au/node/apni/2912741","https://id.biodiversity.org.au/node/apni/2913369","https://id.biodiversity.org.au/node/apni/2913556","https://id.biodiversity.org.au/node/apni/2914040","https://id.biodiversity.org.au/node/apni/2914179","https://id.biodiversity.org.au/node/apni/2914565","https://id.biodiversity.org.au/node/apni/2915629","https://id.biodiversity.org.au/node/apni/2915872","https://id.biodiversity.org.au/node/apni/2916843","https://id.biodiversity.org.au/node/apni/2919557","https://id.biodiversity.org.au/node/apni/2920577","https://id.biodiversity.org.au/node/apni/2920819","https://id.biodiversity.org.au/node/apni/2920955","https://id.biodiversity.org.au/node/apni/6986247","https://id.biodiversity.org.au/node/apni/6990396","https://id.biodiversity.org.au/node/apni/7063134","https://id.biodiversity.org.au/node/apni/7385749","https://id.biodiversity.org.au/taxon/apni/51269276","https://id.biodiversity.org.au/taxon/apni/51283673","https://id.biodiversity.org.au/taxon/apni/51287746","Not supplied"],"link":"https://biocache.ala.org.au/occurrences/search?file=records-2020-02-25&reasonTypeId=3&dwcHeaders=true&fileType=csv&qa=none&sourceTypeId=0&email=[REDACTED]%40[REDACTED]&q=*%3A*&fq=geospatial_kosher%3Atrue&fq=species_group%3APlants&lat=-37.8448&lon=145.3847&radius=1.0&&pageSize=0&&facet=true&","title":"This document was generated on 25 February 2020"},"lon":"145.3847","fq":"[Ljava.lang.String;@11a828cc","sourceTypeId":"0","facets":"species_guid","qa":"none","q":"*:*","file":"records-2020-02-25","reasonTypeId":"3","action":"offline","radius":"1.0","fileType":"csv","email":"[REDACTED]@[REDACTED]","lat":"-37.8448","fileRef":"26022020-fieldguide1582688441393.pdf","status":"running"} > Cache collectionMetadata already exists
net.sf.ehcache.ObjectExistsException: Cache collectionMetadata already exists
	at net.sf.ehcache.CacheManager.addCacheNoCheck(CacheManager.java:1115)
	at net.sf.ehcache.CacheManager.addCache(CacheManager.java:1006)
	at net.sf.ehcache.CacheManager.addCache(CacheManager.java:959)
	at grails.plugin.cache.ehcache.GrailsEhcacheCacheManager.getCache(GrailsEhcacheCacheManager.java:60)
	at au.org.ala.GenerateService$_getSortedTaxonInfo_closure2.doCall(GenerateService.groovy:164)
	at au.org.ala.GenerateService.getSortedTaxonInfo(GenerateService.groovy:155)
	at au.org.ala.GenerateService.generate(GenerateService.groovy:40)
	at au.org.ala.QueueService$ConsumerThread.run(QueueService.groovy:216)
```

**Comment by adam-collins** [comment]
Problem is resolved because we are no longer running fieldguide in the same tomcat instance as other applications.
